### ISSUE TITLE
BitSet API

### ISSUE THREAD

**Issue by infusion** [tdzienniak/entropy#3]
Hi,

I'm the author of BitSet.js and as you rely on this lib (even a quite old version), I want to notify you, that I changed the API of BitSet with version 3.0.0 that method invocations no longer change the state of the actual object, but return a new object.

Making BitSet immutable was a big step, but I think it makes things more reliable. I just browsed your code and found 3 occurrences which should be changed in order to work with 3.0. 

Sorry for any inconveniences.

Robert

**Comment by tdzienniak** [comment]
Hey,

I have noticed the changes in API of BitSet, that's why I stick with older version. But I will update to newer version soon and then I will make changes to my code. Thanks for letting me know! :)

**Comment by infusion** [comment]
You're welcome :) I think it's okay to close that "issue" then.
