### ISSUE TITLE
Explain reversed start/stop of system event responses

### ISSUE THREAD

**Issue by mk-pmb** [tdzienniak/entropy#8]
In `packages/entropy/src/System.js`, the `this.stopResponding();` and `this.startResponding();` look swapped. The comments basically rephrase the code, explaining only that it's about events, but what I wonder a lot more is: Why should a system respond to events when _disabled_, and not respond when _enabled_?

**Comment by tdzienniak** [comment]
It's a bug, thanks for pointing it. I will fix this today after work.

**Comment by mk-pmb** [comment]
Now I wonder how your demo games could have worked when enable/disable is swapped.

**Comment by tdzienniak** [comment]
I simply didn't use this functionality in my demo games. I plan to write test for all features, so bugs like this will be caught.
